"""add workflows

Revision ID: 25d7415163b1
Revises: f2b7c4d9e801
Create Date: 2026-06-01 18:12:37.670877

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "25d7415163b1"
down_revision: Union[str, Sequence[str], None] = "f2b7c4d9e801"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "automation_workflows",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("teaser", sa.String(length=500), nullable=False),
        sa.Column("class", sa.Enum("system", "plugin", name="automationworkflowclass"), nullable=False),
        sa.Column("description", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("link", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_automation_workflows_name"), "automation_workflows", ["name"], unique=False)
    op.create_table(
        "automation_workflow_categories",
        sa.Column("automation_workflow_id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["automation_workflow_id"], ["automation_workflows.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("automation_workflow_id", "category_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("automation_workflow_categories")
    op.drop_index(op.f("ix_automation_workflows_name"), table_name="automation_workflows")
    op.drop_table("automation_workflows")
    # ### end Alembic commands ###
