"""Content Refactor

Revision ID: 27eb42466e5a
Revises: d7ef1b36bbda
Create Date: 2026-04-21 22:53:57.597078

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "27eb42466e5a"
down_revision: Union[str, Sequence[str], None] = "d7ef1b36bbda"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "content",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("summary", sa.String(length=500), nullable=False),
        sa.Column("author", sa.String(length=120), nullable=False),
        sa.Column("thumbnail_url", sa.String(length=500), nullable=False),
        sa.Column("type", sa.Enum("BLOG", "CASE_STUDY", name="contenttype"), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_content_slug"), "content", ["slug"], unique=True)
    op.create_table(
        "content_categories",
        sa.Column("content_id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["content_id"], ["content.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("content_id", "category_id"),
    )
    op.drop_table("blog_categories")
    op.drop_index(op.f("ix_blogs_slug"), table_name="blogs")
    op.drop_table("blogs")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blogs",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("slug", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("title", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("summary", sa.VARCHAR(length=500), autoincrement=False, nullable=False),
        sa.Column("author", sa.VARCHAR(length=120), autoincrement=False, nullable=False),
        sa.Column("thumbnail_url", sa.VARCHAR(length=500), autoincrement=False, nullable=False),
        sa.Column("is_published", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("blogs_pkey")),
    )
    op.create_index(op.f("ix_blogs_slug"), "blogs", ["slug"], unique=True)
    op.create_table(
        "blog_categories",
        sa.Column("blog_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("category_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["blog_id"], ["blogs.id"], name=op.f("blog_categories_blog_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["category_id"], ["categories.id"], name=op.f("blog_categories_category_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("blog_id", "category_id", name=op.f("blog_categories_pkey")),
    )
    op.drop_table("content_categories")
    op.drop_index(op.f("ix_content_slug"), table_name="content")
    op.drop_table("content")
    # ### end Alembic commands ###
