"""Add thumbnail url to blog

Revision ID: 34eb81479368
Revises: 8e05d5711479
Create Date: 2026-04-14 18:24:47.109847

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "34eb81479368"
down_revision: Union[str, Sequence[str], None] = "8e05d5711479"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("blogs", sa.Column("thumbnail_url", sa.String(length=500), nullable=False))
    op.alter_column("blogs", "summary", existing_type=sa.VARCHAR(length=500), nullable=False)
    op.alter_column("blogs", "author", existing_type=sa.VARCHAR(length=120), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("blogs", "author", existing_type=sa.VARCHAR(length=120), nullable=True)
    op.alter_column("blogs", "summary", existing_type=sa.VARCHAR(length=500), nullable=True)
    op.drop_column("blogs", "thumbnail_url")
    # ### end Alembic commands ###
