"""content to html and meta tags

Revision ID: 860737e02249
Revises: 8aa215e41580
Create Date: 2026-05-04 19:19:29.874017

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "860737e02249"
down_revision: Union[str, Sequence[str], None] = "8aa215e41580"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("content", sa.Column("meta_tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column(
        "content",
        "content",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.String(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "content",
        "content",
        existing_type=sa.String(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.drop_column("content", "meta_tags")
    # ### end Alembic commands ###
