"""add submission table

Revision ID: a01e22766edc
Revises: b6b4f1ce4f2a
Create Date: 2026-05-22 15:28:32.895994

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a01e22766edc"
down_revision: Union[str, Sequence[str], None] = "b6b4f1ce4f2a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contact_submissions",
        sa.Column("contact_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("company", sa.String(length=200), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=True),
        sa.Column("journey", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["contact_id"], ["contacts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column("contacts", "email", existing_type=sa.VARCHAR(length=255), nullable=False)
    op.drop_index(op.f("ix_contacts_email"), table_name="contacts")
    op.create_index(op.f("ix_contacts_email"), "contacts", ["email"], unique=True)
    op.drop_column("contacts", "name")
    op.drop_column("contacts", "phone")
    op.drop_column("contacts", "updated_at")
    op.drop_column("contacts", "journey")
    op.drop_column("contacts", "company")
    op.drop_column("contacts", "source")
    op.drop_column("contacts", "message")
    op.drop_column("contacts", "created_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contacts",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column("contacts", sa.Column("message", sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column("contacts", sa.Column("source", sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column("contacts", sa.Column("company", sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column(
        "contacts", sa.Column("journey", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True)
    )
    op.add_column(
        "contacts",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column("contacts", sa.Column("phone", sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column("contacts", sa.Column("name", sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_index(op.f("ix_contacts_email"), table_name="contacts")
    op.create_index(op.f("ix_contacts_email"), "contacts", ["email"], unique=False)
    op.alter_column("contacts", "email", existing_type=sa.VARCHAR(length=255), nullable=True)
    op.drop_table("contact_submissions")
    # ### end Alembic commands ###
