"""rename metadata

Revision ID: d5d51f890b58
Revises: e2516668207f
Create Date: 2026-04-27 23:17:13.666613

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d5d51f890b58"
down_revision: Union[str, Sequence[str], None] = "e2516668207f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("contacts", sa.Column("journey", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column("contacts", "metadata_field")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contacts",
        sa.Column("metadata_field", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    )
    op.drop_column("contacts", "journey")
    # ### end Alembic commands ###
