"""Author table and contact metadata

Revision ID: e2516668207f
Revises: 27eb42466e5a
Create Date: 2026-04-24 20:50:45.336407

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e2516668207f"
down_revision: Union[str, Sequence[str], None] = "27eb42466e5a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authors",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("profile_picture_url", sa.String(length=500), nullable=True),
        sa.Column("about", sa.Text(), nullable=True),
        sa.Column("organization", sa.String(length=255), nullable=True),
        sa.Column("position", sa.String(length=255), nullable=True),
        sa.Column("social_links", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("contacts", sa.Column("metadata_field", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column("content", sa.Column("author_id", sa.UUID(), nullable=True))
    op.alter_column(
        "content",
        "content",
        existing_type=sa.TEXT(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        postgresql_using="content::jsonb",
        existing_nullable=False,
    )
    op.create_foreign_key(None, "content", "authors", ["author_id"], ["id"])
    op.drop_column("content", "author")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("content", sa.Column("author", sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_constraint(None, "content", type_="foreignkey")
    op.alter_column(
        "content",
        "content",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.drop_column("content", "author_id")
    op.drop_column("contacts", "metadata_field")
    op.drop_table("authors")
    # ### end Alembic commands ###
