"""add workflows image

Revision ID: ec5714b807cb
Revises: 25d7415163b1
Create Date: 2026-06-01 18:21:19.900595

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ec5714b807cb"
down_revision: Union[str, Sequence[str], None] = "25d7415163b1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("automation_workflows", sa.Column("thumbnail_url", sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("automation_workflows", "thumbnail_url")
    # ### end Alembic commands ###
