"""Add status table

Revision ID: fc2340555d82
Revises: 699a836587ae
Create Date: 2026-06-10 18:39:10.388577

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "fc2340555d82"
down_revision: Union[str, Sequence[str], None] = "699a836587ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "statuses",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("contacts", sa.Column("status_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        "fk_contacts_status_id_statuses", "contacts", "statuses", ["status_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_contacts_status_id_statuses", "contacts", type_="foreignkey")
    op.drop_column("contacts", "status_id")
    op.drop_table("statuses")
    # ### end Alembic commands ###
